#! /bin/sh

picom --experimental-backends & # Compositor
~/.config/scripts/launch_polybar.sh & # Status bar
~/.config/scripts/screens.sh &
dunst & # Notifications
feh --bg-fill ~/Pictures/wallpaper2.jpg & # Wallpaper
/usr/lib/polkit-kde-authentication-agent-1 & # Auth agent
numlockx on # Enable numlock
sxhkd & # Keyboard shortcuts

bspc monitor DisplayPort-2 -d 1 2 3 4
bspc monitor DisplayPort-1 -d 5 6 7 8 9 10
bspc monitor HDMI-A-0 -d 11 12 13 14
 
bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

